ITU_CALLSIGN_PREFIXES = [
    ("HB3Y", "Liechtenstein", "LI"),
    ("HB0", "Liechtenstein", "LI"),
    ("HBL", "Liechtenstein", "LI"),
    ("SSA", "Egypt", "EG"),
    ("SSB", "Egypt", "EG"),
    ("SSC", "Egypt", "EG"),
    ("SSD", "Egypt", "EG"),
    ("SSE", "Egypt", "EG"),
    ("SSF", "Egypt", "EG"),
    ("SSG", "Egypt", "EG"),
    ("SSH", "Egypt", "EG"),
    ("SSI", "Egypt", "EG"),
    ("SSJ", "Egypt", "EG"),
    ("SSK", "Egypt", "EG"),
    ("SSL", "Egypt", "EG"),
    ("SSM", "Egypt", "EG"),
    ("SSN", "Sudan", "SD"),
    ("SSO", "Sudan", "SD"),
    ("SSP", "Sudan", "SD"),
    ("SSQ", "Sudan", "SD"),
    ("SSR", "Sudan", "SD"),
    ("SSS", "Sudan", "SD"),
    ("SST", "Sudan", "SD"),
    ("SSU", "Sudan", "SD"),
    ("SSV", "Sudan", "SD"),
    ("SSW", "Sudan", "SD"),
    ("SSX", "Sudan", "SD"),
    ("SSY", "Sudan", "SD"),
    ("SSZ", "Sudan", "SD"),
    ("3DA", "Eswatini", "SZ"),
    ("3DB", "Eswatini", "SZ"),
    ("3DC", "Eswatini", "SZ"),
    ("3DD", "Eswatini", "SZ"),
    ("3DE", "Eswatini", "SZ"),
    ("3DF", "Eswatini", "SZ"),
    ("3DG", "Eswatini", "SZ"),
    ("3DH", "Eswatini", "SZ"),
    ("3DI", "Eswatini", "SZ"),
    ("3DJ", "Eswatini", "SZ"),
    ("3DK", "Eswatini", "SZ"),
    ("3DL", "Eswatini", "SZ"),
    ("3DM", "Eswatini", "SZ"),
    ("3DN", "Fiji", "FJ"),
    ("3DO", "Fiji", "FJ"),
    ("3DP", "Fiji", "FJ"),
    ("3DQ", "Fiji", "FJ"),
    ("3DR", "Fiji", "FJ"),
    ("3DS", "Fiji", "FJ"),
    ("3DT", "Fiji", "FJ"),
    ("3DU", "Fiji", "FJ"),
    ("3DV", "Fiji", "FJ"),
    ("3DW", "Fiji", "FJ"),
    ("3DX", "Fiji", "FJ"),
    ("3DY", "Fiji", "FJ"),
    ("3DZ", "Fiji", "FJ"),
    ("AA", "United States", "US"),
    ("AB", "United States", "US"),
    ("AC", "United States", "US"),
    ("AD", "United States", "US"),
    ("AE", "United States", "US"),
    ("AF", "United States", "US"),
    ("AG", "United States", "US"),
    ("AH", "United States", "US"),
    ("AI", "United States", "US"),
    ("AJ", "United States", "US"),
    ("AK", "United States", "US"),
    ("AL", "United States", "US"),
    ("AM", "Spain", "ES"),
    ("AN", "Spain", "ES"),
    ("AO", "Spain", "ES"),
    ("AP", "Pakistan", "PK"),
    ("AQ", "Pakistan", "PK"),
    ("AR", "Pakistan", "PK"),
    ("AS", "Pakistan", "PK"),
    ("AT", "India", "IN"),
    ("AU", "India", "IN"),
    ("AV", "India", "IN"),
    ("AW", "India", "IN"),
    ("AX", "Australia", "AU"),
    ("AY", "Argentina", "AR"),
    ("AZ", "Argentina", "AR"),
    ("A2", "Botswana", "BW"),
    ("A3", "Tonga", "TO"),
    ("A4", "Oman", "OM"),
    ("A5", "Bhutan", "BT"),
    ("A6", "United Arab Emirates", "AE"),
    ("A7", "Qatar", "QA"),
    ("A8", "Liberia", "LR"),
    ("A9", "Bahrain", "BH"),
    ("BM", "Taiwan", "TW"),
    ("BN", "Taiwan", "TW"),
    ("BO", "Taiwan", "TW"),
    ("BP", "Taiwan", "TW"),
    ("BQ", "Taiwan", "TW"),
    ("BU", "Taiwan", "TW"),
    ("BV", "Taiwan", "TW"),
    ("BW", "Taiwan", "TW"),
    ("BX", "Taiwan", "TW"),
    ("CA", "Chile", "CL"),
    ("CB", "Chile", "CL"),
    ("CC", "Chile", "CL"),
    ("CD", "Chile", "CL"),
    ("CE", "Chile", "CL"),
    ("CF", "Canada", "CA"),
    ("CG", "Canada", "CA"),
    ("CH", "Canada", "CA"),
    ("CI", "Canada", "CA"),
    ("CJ", "Canada", "CA"),
    ("CK", "Canada", "CA"),
    ("CL", "Cuba", "CU"),
    ("CM", "Cuba", "CU"),
    ("CN", "Morocco", "MA"),
    ("CO", "Cuba", "CU"),
    ("CP", "Bolivia", "BO"),
    ("CQ", "Portugal", "PT"),
    ("CR", "Portugal", "PT"),
    ("CS", "Portugal", "PT"),
    ("CT", "Portugal", "PT"),
    ("CU", "Portugal", "PT"),
    ("CV", "Uruguay", "UY"),
    ("CW", "Uruguay", "UY"),
    ("CX", "Uruguay", "UY"),
    ("CY", "Canada", "CA"),
    ("CZ", "Canada", "CA"),
    ("C2", "Nauru", "NR"),
    ("C3", "Andorra", "AD"),
    ("C4", "Cyprus", "CY"),
    ("C5", "The Gambia", "GM"),
    ("C6", "Bahamas", "BS"),
    ("C7", "World Meteorological Organization", None),
    ("C8", "Mozambique", "MZ"),
    ("C9", "Mozambique", "MZ"),
    ("DA", "Germany", "DE"),
    ("DB", "Germany", "DE"),
    ("DC", "Germany", "DE"),
    ("DD", "Germany", "DE"),
    ("DE", "Germany", "DE"),
    ("DF", "Germany", "DE"),
    ("DG", "Germany", "DE"),
    ("DH", "Germany", "DE"),
    ("DI", "Germany", "DE"),
    ("DJ", "Germany", "DE"),
    ("DK", "Germany", "DE"),
    ("DL", "Germany", "DE"),
    ("DM", "Germany", "DE"),
    ("DN", "Germany", "DE"),
    ("DO", "Germany", "DE"),
    ("DP", "Germany", "DE"),
    ("DQ", "Germany", "DE"),
    ("DR", "Germany", "DE"),
    ("DS", "South Korea", "KR"),
    ("DT", "South Korea", "KR"),
    ("DU", "Philippines", "PH"),
    ("DV", "Philippines", "PH"),
    ("DW", "Philippines", "PH"),
    ("DX", "Philippines", "PH"),
    ("DY", "Philippines", "PH"),
    ("DZ", "Philippines", "PH"),
    ("D2", "Angola", "AO"),
    ("D3", "Angola", "AO"),
    ("D4", "Cape Verde", "CV"),
    ("D5", "Liberia", "LR"),
    ("D6", "Comoros", "KM"),
    ("D7", "South Korea", "KR"),
    ("D8", "South Korea", "KR"),
    ("D9", "South Korea", "KR"),
    ("EA", "Spain", "ES"),
    ("EB", "Spain", "ES"),
    ("EC", "Spain", "ES"),
    ("ED", "Spain", "ES"),
    ("EE", "Spain", "ES"),
    ("EF", "Spain", "ES"),
    ("EG", "Spain", "ES"),
    ("EH", "Spain", "ES"),
    ("EI", "Ireland", "IE"),
    ("EJ", "Ireland", "IE"),
    ("EK", "Armenia", "AM"),
    ("EL", "Liberia", "LR"),
    ("EM", "Ukraine", "UA"),
    ("EN", "Ukraine", "UA"),
    ("EO", "Ukraine", "UA"),
    ("EP", "Iran", "IR"),
    ("EQ", "Iran", "IR"),
    ("ER", "Moldova", "MD"),
    ("ES", "Estonia", "EE"),
    ("ET", "Ethiopia", "ET"),
    ("EU", "Belarus", "BY"),
    ("EV", "Belarus", "BY"),
    ("EW", "Belarus", "BY"),
    ("EX", "Kyrgyzstan", "KG"),
    ("EY", "Tajikistan", "TJ"),
    ("EZ", "Turkmenistan", "TM"),
    ("E2", "Thailand", "TH"),
    ("E3", "Eritrea", "ER"),
    ("E4", "Palestinian Authority", "PS"),
    ("E5", "Cook Islands", "CK"),
    ("E7", "Bosnia-Herzegovina", "BA"),
    ("HA", "Hungary", "HU"),
    ("HB", "Switzerland", "CH"),
    ("HC", "Ecuador", "EC"),
    ("HD", "Ecuador", "EC"),
    ("HE", "Switzerland", "CH"),
    ("HF", "Poland", "PL"),
    ("HG", "Hungary", "HU"),
    ("HH", "Haiti", "HT"),
    ("HI", "Dominican Republic", "DO"),
    ("HJ", "Colombia", "CO"),
    ("HK", "Colombia", "CO"),
    ("HL", "South Korea", "KR"),
    ("HM", "North Korea", "KP"),
    ("HN", "Iraq", "IQ"),
    ("HO", "Panama", "PA"),
    ("HP", "Panama", "PA"),
    ("HQ", "Honduras", "HN"),
    ("HR", "Honduras", "HN"),
    ("HS", "Thailand", "TH"),
    ("HT", "Nicaragua", "NI"),
    ("HU", "El Salvador", "SV"),
    ("HV", "Vatican City", "VA"),
    ("HW", "France", "FR"),
    ("HX", "France", "FR"),
    ("HY", "France", "FR"),
    ("HZ", "Saudi Arabia", "SA"),
    ("H2", "Cyprus", "CY"),
    ("H3", "Panama", "PA"),
    ("H4", "Solomon Islands", "SB"),
    ("H6", "Nicaragua", "NI"),
    ("H7", "Nicaragua", "NI"),
    ("H8", "Panama", "PA"),
    ("H9", "Panama", "PA"),
    ("JA", "Japan", "JP"),
    ("JB", "Japan", "JP"),
    ("JC", "Japan", "JP"),
    ("JD", "Japan", "JP"),
    ("JE", "Japan", "JP"),
    ("JF", "Japan", "JP"),
    ("JG", "Japan", "JP"),
    ("JH", "Japan", "JP"),
    ("JI", "Japan", "JP"),
    ("JJ", "Japan", "JP"),
    ("JK", "Japan", "JP"),
    ("JL", "Japan", "JP"),
    ("JM", "Japan", "JP"),
    ("JN", "Japan", "JP"),
    ("JO", "Japan", "JP"),
    ("JP", "Japan", "JP"),
    ("JQ", "Japan", "JP"),
    ("JR", "Japan", "JP"),
    ("JS", "Japan", "JP"),
    ("JT", "Mongolia", "MN"),
    ("JU", "Mongolia", "MN"),
    ("JV", "Mongolia", "MN"),
    ("JW", "Norway", "NO"),
    ("JX", "Norway", "NO"),
    ("JY", "Jordan", "JO"),
    ("JZ", "Indonesia", "ID"),
    ("J2", "Djibouti", "DJ"),
    ("J3", "Grenada", "GD"),
    ("J4", "Greece", "GR"),
    ("J5", "Guinea-Bissau", "GW"),
    ("J6", "Saint Lucia", "LC"),
    ("J7", "Dominica", "DM"),
    ("J8", "Saint Vincent and the Grenadines", "VC"),
    ("LA", "Norway", "NO"),
    ("LB", "Norway", "NO"),
    ("LC", "Norway", "NO"),
    ("LD", "Norway", "NO"),
    ("LE", "Norway", "NO"),
    ("LF", "Norway", "NO"),
    ("LG", "Norway", "NO"),
    ("LH", "Norway", "NO"),
    ("LI", "Norway", "NO"),
    ("LJ", "Norway", "NO"),
    ("LK", "Norway", "NO"),
    ("LL", "Norway", "NO"),
    ("LM", "Norway", "NO"),
    ("LN", "Norway", "NO"),
    ("LO", "Argentina", "AR"),
    ("LP", "Argentina", "AR"),
    ("LQ", "Argentina", "AR"),
    ("LR", "Argentina", "AR"),
    ("LS", "Argentina", "AR"),
    ("LT", "Argentina", "AR"),
    ("LU", "Argentina", "AR"),
    ("LV", "Argentina", "AR"),
    ("LW", "Argentina", "AR"),
    ("LX", "Luxembourg", "LU"),
    ("LY", "Lithuania", "LT"),
    ("LZ", "Bulgaria", "BG"),
    ("L2", "Argentina", "AR"),
    ("L3", "Argentina", "AR"),
    ("L4", "Argentina", "AR"),
    ("L5", "Argentina", "AR"),
    ("L6", "Argentina", "AR"),
    ("L7", "Argentina", "AR"),
    ("L8", "Argentina", "AR"),
    ("L9", "Argentina", "AR"),
    ("OA", "Peru", "PE"),
    ("OB", "Peru", "PE"),
    ("OC", "Peru", "PE"),
    ("OD", "Lebanon", "LB"),
    ("OE", "Austria", "AT"),
    ("OF", "Finland", "FI"),
    ("OG", "Finland", "FI"),
    ("OH", "Finland", "FI"),
    ("OI", "Finland", "FI"),
    ("OJ", "Finland", "FI"),
    ("OK", "Czech Republic", "CZ"),
    ("OL", "Czech Republic", "CZ"),
    ("OM", "Slovakia", "SK"),
    ("ON", "Belgium", "BE"),
    ("OO", "Belgium", "BE"),
    ("OP", "Belgium", "BE"),
    ("OQ", "Belgium", "BE"),
    ("OR", "Belgium", "BE"),
    ("OS", "Belgium", "BE"),
    ("OT", "Belgium", "BE"),
    ("OU", "Denmark", "DK"),
    ("OV", "Denmark", "DK"),
    ("OW", "Denmark", "DK"),
    ("OX", "Denmark", "DK"),
    ("OY", "Denmark", "DK"),
    ("OZ", "Denmark", "DK"),
    ("PA", "Netherlands", "NL"),
    ("PB", "Netherlands", "NL"),
    ("PC", "Netherlands", "NL"),
    ("PD", "Netherlands", "NL"),
    ("PE", "Netherlands", "NL"),
    ("PF", "Netherlands", "NL"),
    ("PG", "Netherlands", "NL"),
    ("PH", "Netherlands", "NL"),
    ("PI", "Netherlands", "NL"),
    ("PJ", "Netherlands", "NL"),
    ("PK", "Indonesia", "ID"),
    ("PL", "Indonesia", "ID"),
    ("PM", "Indonesia", "ID"),
    ("PN", "Indonesia", "ID"),
    ("PO", "Indonesia", "ID"),
    ("PP", "Brazil", "BR"),
    ("PQ", "Brazil", "BR"),
    ("PR", "Brazil", "BR"),
    ("PS", "Brazil", "BR"),
    ("PT", "Brazil", "BR"),
    ("PU", "Brazil", "BR"),
    ("PV", "Brazil", "BR"),
    ("PW", "Brazil", "BR"),
    ("PX", "Brazil", "BR"),
    ("PY", "Brazil", "BR"),
    ("PZ", "Suriname", "SR"),
    ("P2", "Papua New Guinea", "PG"),
    ("P3", "Cyprus", "CY"),
    ("P4", "Aruba", "AW"),
    ("P5", "North Korea", "KP"),
    ("P6", "North Korea", "KP"),
    ("P7", "North Korea", "KP"),
    ("P8", "North Korea", "KP"),
    ("P9", "North Korea", "KP"),
    ("SA", "Sweden", "SE"),
    ("SB", "Sweden", "SE"),
    ("SC", "Sweden", "SE"),
    ("SD", "Sweden", "SE"),
    ("SE", "Sweden", "SE"),
    ("SF", "Sweden", "SE"),
    ("SG", "Sweden", "SE"),
    ("SH", "Sweden", "SE"),
    ("SI", "Sweden", "SE"),
    ("SJ", "Sweden", "SE"),
    ("SK", "Sweden", "SE"),
    ("SL", "Sweden", "SE"),
    ("SM", "Sweden", "SE"),
    ("SN", "Poland", "PL"),
    ("SO", "Poland", "PL"),
    ("SP", "Poland", "PL"),
    ("SQ", "Poland", "PL"),
    ("SR", "Poland", "PL"),
    ("ST", "Sudan", "SD"),
    ("SU", "Egypt", "EG"),
    ("SV", "Greece", "GR"),
    ("SW", "Greece", "GR"),
    ("SX", "Greece", "GR"),
    ("SY", "Greece", "GR"),
    ("SZ", "Greece", "GR"),
    ("S2", "Bangladesh", "BD"),
    ("S3", "Bangladesh", "BD"),
    ("S5", "Slovenia", "SI"),
    ("S6", "Singapore", "SG"),
    ("S7", "Seychelles", "SC"),
    ("S8", "South Africa", "ZA"),
    ("S9", "Sao Tome and Principe", "ST"),
    ("TA", "Turkey", "TR"),
    ("TB", "Turkey", "TR"),
    ("TC", "Turkey", "TR"),
    ("TD", "Guatemala", "GT"),
    ("TE", "Costa Rica", "CR"),
    ("TF", "Iceland", "IS"),
    ("TG", "Guatemala", "GT"),
    ("TH", "France", "FR"),
    ("TI", "Costa Rica", "CR"),
    ("TJ", "Cameroon", "CM"),
    ("TK", "France", "FR"),
    ("TL", "Central African Republic", "CF"),
    ("TM", "France", "FR"),
    ("TN", "Congo", "CG"),
    ("TO", "France", "FR"),
    ("TP", "France", "FR"),
    ("TQ", "France", "FR"),
    ("TR", "Gabon", "GA"),
    ("TS", "Tunisia", "TN"),
    ("TT", "Chad", "TD"),
    ("TU", "Cote d'Ivoire", "CI"),
    ("TV", "France", "FR"),
    ("TW", "France", "FR"),
    ("TX", "France", "FR"),
    ("TY", "Benin", "BJ"),
    ("TZ", "Mali", "ML"),
    ("T2", "Tuvalu", "TV"),
    ("T3", "Kiribati", "KI"),
    ("T4", "Cuba", "CU"),
    ("T5", "Somalia", "SO"),
    ("T6", "Afghanistan", "AF"),
    ("T7", "San Marino", "SM"),
    ("T8", "Palau", "PW"),
    ("T9", "Bosnia-Herzegovina", "BA"),
    ("UA", "Russia", "RU"),
    ("UB", "Russia", "RU"),
    ("UC", "Russia", "RU"),
    ("UD", "Russia", "RU"),
    ("UE", "Russia", "RU"),
    ("UF", "Russia", "RU"),
    ("UG", "Russia", "RU"),
    ("UH", "Russia", "RU"),
    ("UI", "Russia", "RU"),
    ("UJ", "Uzbekistan", "UZ"),
    ("UK", "Uzbekistan", "UZ"),
    ("UL", "Uzbekistan", "UZ"),
    ("UM", "Uzbekistan", "UZ"),
    ("UN", "Kazakhstan", "KZ"),
    ("UO", "Kazakhstan", "KZ"),
    ("UP", "Kazakhstan", "KZ"),
    ("UQ", "Kazakhstan", "KZ"),
    ("UR", "Ukraine", "UA"),
    ("US", "Ukraine", "UA"),
    ("UT", "Ukraine", "UA"),
    ("UU", "Ukraine", "UA"),
    ("UV", "Ukraine", "UA"),
    ("UW", "Ukraine", "UA"),
    ("UX", "Ukraine", "UA"),
    ("UY", "Ukraine", "UA"),
    ("UZ", "Ukraine", "UA"),
    ("VA", "Canada", "CA"),
    ("VB", "Canada", "CA"),
    ("VC", "Canada", "CA"),
    ("VD", "Canada", "CA"),
    ("VE", "Canada", "CA"),
    ("VF", "Canada", "CA"),
    ("VG", "Canada", "CA"),
    ("VH", "Australia", "AU"),
    ("VI", "Australia", "AU"),
    ("VJ", "Australia", "AU"),
    ("VK", "Australia", "AU"),
    ("VL", "Australia", "AU"),
    ("VM", "Australia", "AU"),
    ("VN", "Australia", "AU"),
    ("VO", "Canada", "CA"),
    ("VP", "United Kingdom", "GB"),
    ("VQ", "United Kingdom", "GB"),
    ("VR", "Hong Kong", "HK"),
    ("VS", "United Kingdom", "GB"),
    ("VT", "India", "IN"),
    ("VU", "India", "IN"),
    ("VV", "India", "IN"),
    ("VW", "India", "IN"),
    ("VX", "Canada", "CA"),
    ("VY", "Canada", "CA"),
    ("VZ", "Australia", "AU"),
    ("V2", "Antigua and Barbuda", "AG"),
    ("V3", "Belize", "BZ"),
    ("V4", "Saint Kitts and Nevis", "KN"),
    ("V5", "Namibia", "NA"),
    ("V6", "Federated States of Micronesia", "FM"),
    ("V7", "Marshall Islands", "MH"),
    ("V8", "Brunei", "BN"),
    ("XA", "Mexico", "MX"),
    ("XB", "Mexico", "MX"),
    ("XC", "Mexico", "MX"),
    ("XD", "Mexico", "MX"),
    ("XE", "Mexico", "MX"),
    ("XF", "Mexico", "MX"),
    ("XG", "Mexico", "MX"),
    ("XH", "Mexico", "MX"),
    ("XI", "Mexico", "MX"),
    ("XJ", "Canada", "CA"),
    ("XK", "Canada", "CA"),
    ("XL", "Canada", "CA"),
    ("XM", "Canada", "CA"),
    ("XN", "Canada", "CA"),
    ("XO", "Canada", "CA"),
    ("XP", "Denmark", "DK"),
    ("XQ", "Chile", "CL"),
    ("XR", "Chile", "CL"),
    ("XS", "People's Republic of China", "CN"),
    ("XT", "Burkina Faso", "BF"),
    ("XU", "Cambodia", "KH"),
    ("XV", "Vietnam", "VN"),
    ("XW", "Laos", "LA"),
    ("XX", "Macao", "MO"),
    ("XY", "Myanmar", "MM"),
    ("XZ", "Myanmar", "MM"),
    ("YA", "Afghanistan", "AF"),
    ("YB", "Indonesia", "ID"),
    ("YC", "Indonesia", "ID"),
    ("YD", "Indonesia", "ID"),
    ("YE", "Indonesia", "ID"),
    ("YF", "Indonesia", "ID"),
    ("YG", "Indonesia", "ID"),
    ("YH", "Indonesia", "ID"),
    ("YI", "Iraq", "IQ"),
    ("YJ", "Vanuatu", "VU"),
    ("YK", "Syria", "SY"),
    ("YL", "Latvia", "LV"),
    ("YM", "Turkey", "TR"),
    ("YN", "Nicaragua", "NI"),
    ("YO", "Romania", "RO"),
    ("YP", "Romania", "RO"),
    ("YQ", "Romania", "RO"),
    ("YR", "Romania", "RO"),
    ("YS", "El Salvador", "SV"),
    ("YT", "Serbia", "RS"),
    ("YU", "Serbia", "RS"),
    ("YV", "Venezuela", "VE"),
    ("YW", "Venezuela", "VE"),
    ("YX", "Venezuela", "VE"),
    ("YY", "Venezuela", "VE"),
    ("Y2", "Germany", "DE"),
    ("Y3", "Germany", "DE"),
    ("Y4", "Germany", "DE"),
    ("Y5", "Germany", "DE"),
    ("Y6", "Germany", "DE"),
    ("Y7", "Germany", "DE"),
    ("Y8", "Germany", "DE"),
    ("Y9", "Germany", "DE"),
    ("ZA", "Albania", "AL"),
    ("ZB", "United Kingdom", "GB"),
    ("ZC", "United Kingdom", "GB"),
    ("ZD", "United Kingdom", "GB"),
    ("ZE", "United Kingdom", "GB"),
    ("ZF", "United Kingdom", "GB"),
    ("ZG", "United Kingdom", "GB"),
    ("ZH", "United Kingdom", "GB"),
    ("ZI", "United Kingdom", "GB"),
    ("ZJ", "United Kingdom", "GB"),
    ("ZK", "New Zealand", "NZ"),
    ("ZL", "New Zealand", "NZ"),
    ("ZM", "New Zealand", "NZ"),
    ("ZN", "United Kingdom", "GB"),
    ("ZO", "United Kingdom", "GB"),
    ("ZP", "Paraguay", "PY"),
    ("ZQ", "United Kingdom", "GB"),
    ("ZR", "South Africa", "ZA"),
    ("ZS", "South Africa", "ZA"),
    ("ZT", "South Africa", "ZA"),
    ("ZU", "South Africa", "ZA"),
    ("ZV", "Brazil", "BR"),
    ("ZW", "Brazil", "BR"),
    ("ZX", "Brazil", "BR"),
    ("ZY", "Brazil", "BR"),
    ("ZZ", "Brazil", "BR"),
    ("Z2", "Zimbabwe", "ZW"),
    ("Z3", "North Macedonia", "MK"),
    ("Z8", "South Sudan", "SS"),
    ("3A", "Monaco", "MC"),
    ("3B", "Mauritius", "MU"),
    ("3C", "Equatorial Guinea", "GQ"),
    ("3E", "Panama", "PA"),
    ("3F", "Panama", "PA"),
    ("3G", "Chile", "CL"),
    ("3H", "People's Republic of China", "CN"),
    ("3I", "People's Republic of China", "CN"),
    ("3J", "People's Republic of China", "CN"),
    ("3K", "People's Republic of China", "CN"),
    ("3L", "People's Republic of China", "CN"),
    ("3M", "People's Republic of China", "CN"),
    ("3N", "People's Republic of China", "CN"),
    ("3O", "People's Republic of China", "CN"),
    ("3P", "People's Republic of China", "CN"),
    ("3Q", "People's Republic of China", "CN"),
    ("3R", "People's Republic of China", "CN"),
    ("3S", "People's Republic of China", "CN"),
    ("3T", "People's Republic of China", "CN"),
    ("3U", "People's Republic of China", "CN"),
    ("3V", "Tunisia", "TN"),
    ("3W", "Vietnam", "VN"),
    ("3X", "Guinea", "GN"),
    ("3Y", "Norway", "NO"),
    ("3Z", "Poland", "PL"),
    ("4A", "Mexico", "MX"),
    ("4B", "Mexico", "MX"),
    ("4C", "Mexico", "MX"),
    ("4D", "Philippines", "PH"),
    ("4E", "Philippines", "PH"),
    ("4F", "Philippines", "PH"),
    ("4G", "Philippines", "PH"),
    ("4H", "Philippines", "PH"),
    ("4I", "Philippines", "PH"),
    ("4J", "Azerbaijan", "AZ"),
    ("4K", "Azerbaijan", "AZ"),
    ("4L", "Georgia", "GE"),
    ("4M", "Venezuela", "VE"),
    ("4O", "Montenegro", "ME"),
    ("4P", "Sri Lanka", "LK"),
    ("4Q", "Sri Lanka", "LK"),
    ("4R", "Sri Lanka", "LK"),
    ("4S", "Sri Lanka", "LK"),
    ("4T", "Peru", "PE"),
    ("4U", "United Nations", None),
    ("4V", "Haiti", "HT"),
    ("4W", "East Timor", "TL"),
    ("4X", "Israel", "IL"),
    ("4Y", "International Civil Aviation Organization", None),
    ("4Z", "Israel", "IL"),
    ("5A", "Libya", "LY"),
    ("5B", "Cyprus", "CY"),
    ("5C", "Morocco", "MA"),
    ("5D", "Morocco", "MA"),
    ("5E", "Morocco", "MA"),
    ("5F", "Morocco", "MA"),
    ("5G", "Morocco", "MA"),
    ("5H", "Tanzania", "TZ"),
    ("5I", "Tanzania", "TZ"),
    ("5J", "Colombia", "CO"),
    ("5K", "Colombia", "CO"),
    ("5L", "Liberia", "LR"),
    ("5M", "Liberia", "LR"),
    ("5N", "Nigeria", "NG"),
    ("5O", "Nigeria", "NG"),
    ("5P", "Denmark", "DK"),
    ("5Q", "Denmark", "DK"),
    ("5R", "Madagascar", "MG"),
    ("5S", "Madagascar", "MG"),
    ("5T", "Mauritania", "MR"),
    ("5U", "Niger", "NG"),
    ("5V", "Togo", "TG"),
    ("5W", "Western Samoa", "WS"),
    ("5X", "Uganda", "UG"),
    ("5Y", "Kenya", "KE"),
    ("5Z", "Kenya", "KE"),
    ("6A", "Egypt", "EG"),
    ("6B", "Egypt", "EG"),
    ("6C", "Syria", "SY"),
    ("6D", "Mexico", "MX"),
    ("6E", "Mexico", "MX"),
    ("6F", "Mexico", "MX"),
    ("6G", "Mexico", "MX"),
    ("6H", "Mexico", "MX"),
    ("6I", "Mexico", "MX"),
    ("6J", "Mexico", "MX"),
    ("6K", "South Korea", "KR"),
    ("6L", "South Korea", "KR"),
    ("6M", "South Korea", "KR"),
    ("6N", "South Korea", "KR"),
    ("6O", "Somalia", "SO"),
    ("6P", "Pakistan", "PK"),
    ("6Q", "Pakistan", "PK"),
    ("6R", "Pakistan", "PK"),
    ("6S", "Pakistan", "PK"),
    ("6T", "Sudan", "SD"),
    ("6U", "Sudan", "SD"),
    ("6V", "Senegal", "SN"),
    ("6W", "Senegal", "SN"),
    ("6X", "Madagascar", "MG"),
    ("6Y", "Jamaica", "JM"),
    ("6Z", "Liberia", "LR"),
    ("7A", "Indonesia", "ID"),
    ("7B", "Indonesia", "ID"),
    ("7C", "Indonesia", "ID"),
    ("7D", "Indonesia", "ID"),
    ("7E", "Indonesia", "ID"),
    ("7F", "Indonesia", "ID"),
    ("7G", "Indonesia", "ID"),
    ("7H", "Indonesia", "ID"),
    ("7I", "Indonesia", "ID"),
    ("7J", "Japan", "JP"),
    ("7K", "Japan", "JP"),
    ("7L", "Japan", "JP"),
    ("7M", "Japan", "JP"),
    ("7N", "Japan", "JP"),
    ("7O", "Yemen", "YE"),
    ("7P", "Lesotho", "LS"),
    ("7Q", "Malawi", "MW"),
    ("7R", "Algeria", "DZ"),
    ("7S", "Sweden", "SE"),
    ("7T", "Algeria", "DZ"),
    ("7U", "Algeria", "DZ"),
    ("7V", "Algeria", "DZ"),
    ("7W", "Algeria", "DZ"),
    ("7X", "Algeria", "DZ"),
    ("7Y", "Algeria", "DZ"),
    ("7Z", "Saudi Arabia", "SA"),
    ("8A", "Indonesia", "ID"),
    ("8B", "Indonesia", "ID"),
    ("8C", "Indonesia", "ID"),
    ("8D", "Indonesia", "ID"),
    ("8E", "Indonesia", "ID"),
    ("8F", "Indonesia", "ID"),
    ("8G", "Indonesia", "ID"),
    ("8H", "Indonesia", "ID"),
    ("8I", "Indonesia", "ID"),
    ("8J", "Japan", "JP"),
    ("8K", "Japan", "JP"),
    ("8L", "Japan", "JP"),
    ("8M", "Japan", "JP"),
    ("8N", "Japan", "JP"),
    ("8O", "Botswana", "BW"),
    ("8P", "Barbados", "BB"),
    ("8Q", "Maldives", "MV"),
    ("8R", "Guyana", "GY"),
    ("8S", "Sweden", "SE"),
    ("8T", "India", "IN"),
    ("8U", "India", "IN"),
    ("8V", "India", "IN"),
    ("8W", "India", "IN"),
    ("8X", "India", "IN"),
    ("8Y", "India", "IN"),
    ("8Z", "Saudi Arabia", "SA"),
    ("9A", "Croatia", "HR"),
    ("9B", "Iran", "IR"),
    ("9C", "Iran", "IR"),
    ("9D", "Iran", "IR"),
    ("9E", "Ethiopia", "ET"),
    ("9F", "Ethiopia", "ET"),
    ("9G", "Ghana", "GH"),
    ("9H", "Malta", "MT"),
    ("9I", "Zambia", "ZM"),
    ("9J", "Zambia", "ZM"),
    ("9K", "Kuwait", "KW"),
    ("9L", "Sierra Leone", "SL"),
    ("9M", "Malaysia", "MY"),
    ("9N", "Nepal", "NP"),
    ("9O", "Democratic Republic of the Congo", "CG"),
    ("9P", "Democratic Republic of the Congo", "CG"),
    ("9Q", "Democratic Republic of the Congo", "CG"),
    ("9R", "Democratic Republic of the Congo", "CG"),
    ("9S", "Democratic Republic of the Congo", "CG"),
    ("9T", "Democratic Republic of the Congo", "CG"),
    ("9U", "Burundi", "BI"),
    ("9V", "Singapore", "SG"),
    ("9W", "Malaysia", "MY"),
    ("9X", "Rwanda", "RW"),
    ("9Y", "Trinidad and Tobago", "TT"),
    ("9Z", "Trinidad and Tobago", "TT"),
    ("B", "China", "CN"),
    ("F", "France", "FR"),
    ("G", "United Kingdom", "GB"),
    ("I", "Italy", "IT"),
    ("K", "United States", "US"),
    ("M", "United Kingdom", "GB"),
    ("N", "United States", "US"),
    ("R", "Russia", "RU"),
    ("W", "United States", "US"),
    ("2", "United Kingdom", "GB"),
]
